name: datag
description: MVP UI scaffolding for DataG trivia game.
publish_to: "none"

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  flutter_riverpod: ^2.5.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  csv: ^5.0.2
  lucide_icons: ^0.322.0
  shimmer: ^3.0.0
  firebase_core: ^2.31.1
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.4.18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/
