name: datag
description: MVP UI scaffolding for DataG trivia game.
publish_to: "none"

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.4
  intl: ^0.20.2
  shimmer: ^3.0.0
  lucide_flutter: ^0.544.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/
    - assets/events/
